### ISSUE TITLE
WM Lens CT

### ISSUE THREAD

**Issue by pingevt** [bluecadet/riveralive-cms#1]
"WM Lens" CT (wm_lens)

- [ ] remove default body field
- [ ] color (field_lens_color, taxonomy reference to wm_color)
- [ ] icon (field_lens_icon, taxonomy reference to wm_icon)
- [ ] Background Media (field_lens_bg_media -> Media Reference, Image and Video Allowed)
- [ ] Hotspots (field_lens_hotspots, paragraph field, ref to wm_hotspot only, multi-value)

**Comment by ematsakov** [comment]
@pingevt 

`Background Media (field_lens_bg_media -> Media Reference, Image and Video Allowed)`

When we use media of type video on the background. How do we know its aspect radio to set coordinates properly?
Should we add "width" and "height" fields to Video media bundle so editor can enter these params?

**Comment by pingevt** [comment]
@ematsakov Great Question. For co-ordinates, I think what you suggests works.

Also, I could potentially see setting another Image field for a Poster Image. We don't need the poster image but could be good to help define the aspect ratio?

I'll leave it to you to decide, you'll know what's best for the coordinate picker.

**Comment by ematsakov** [comment]
@pingevt 

Done.
http://pr-16-riveralive-cms.pantheonsite.io/admin/structure/types/manage/wm_lens/fields
http://pr-16-riveralive-cms.pantheonsite.io/node/add/wm_lens

Added "Poster Image" for media of type "Video" to be used for setting coordinates
