### ISSUE TITLE
C Results Animal CT

### ISSUE THREAD

**Issue by pingevt** [bluecadet/riveralive-cms#12]
"C Results Animal" CT (c_results_animal)

- [ ] Remove default body field
- [ ] Animal Description (field_c_ranim_desc -> Short Text with WYSIWYG [Don' worry about actual WYSIWYG at the moment])
- [ ] Actions (field_c_actions -> Entity reference fields to "C Actions CT")(Form Display should use Inline Entity Form to be able to create new ones as well as pick existing ones)

**Comment by ematsakov** [comment]
@pingevt 

Done
http://pr-16-riveralive-cms.pantheonsite.io/admin/structure/types/manage/c_results_animal/fields
