### ISSUE TITLE
C Action

### ISSUE THREAD

**Issue by pingevt** [bluecadet/riveralive-cms#14]
"C Action" CT (c_action)

- [ ] Remove Default body field
- [ ] Short description (field_c_desc-> Long Text with WYSIWYG [Don' worry about actual WYSIWYG at the moment])
- [ ] Icon (field_c_icon-> Taxonomy Reference to C Icon, only 1)
- [ ] Image (field_c_img-> Media Ref, image only, only 1)

**Comment by ematsakov** [comment]
@pingevt 

Done
http://pr-16-riveralive-cms.pantheonsite.io/admin/structure/types/manage/c_action/fields
