### ISSUE TITLE
All Media Reference fields Form Display

### ISSUE THREAD

**Issue by pingevt** [bluecadet/riveralive-cms#15]
Pre Req's
- [ ] New Form Mode on media entity (Inline Entity Form)
- [ ] Needed Entity Browsers (Image only, Image & Video)

All Media Reference Fields Form Displays should be:
- [ ] Widget => Inline entity form - Complex
- [ ] Settings: 
- [ ]    Form Mode: Inline Entity Form
- [ ]    Allow users to add new Media: Yes
- [ ]    Allow users to add existing Media: Yes
- [ ]    Entity Browser: (whichever one is applicable for the field)

**Comment by ematsakov** [comment]
@pingevt 

Done
