### ISSUE TITLE
C Action Updates....

### ISSUE THREAD

**Issue by pingevt** [bluecadet/riveralive-cms#29]
First, this now needs to be a paragraph bundle. Data was changed so we need to add coordinate picker and they will no longer be reused. Existing Fields are Good to GO.

- [ ] Change to Paragraph

- [ ] Add Co-ordinate Picker. (this will reference a NEW Image field on C Animal Result)
- [ ] Add Field: Follow (field_c_follow -> Short Text, No WYSIWYG, not required)
- [ ] Add Field: Visit (field_c_visit -> Short Text, No WYSIWYG, not required)

**Comment by aostroverkhov** [comment]
@pingevt just to confirm, what did you mean by "Existing Fields are Good to GO."? Should these field be moved to the new paragraph or are they not needed any more?

**Comment by pingevt** [comment]
They should be moved over to the new paragraph. But nothing needs to be changed for them. 
@aostroverkhov

**Comment by aostroverkhov** [comment]
@pingevt done, please check

**Comment by pingevt** [comment]
Looks Good, Thanks!
