### ISSUE TITLE
WM Hotspot Para Bundle

### ISSUE THREAD

**Issue by pingevt** [bluecadet/riveralive-cms#3]
"WM Hotspot" para bundle (wm_hotspot)

- [ ] (x,y) coords field (Spec from Alexey's team)  ( referencing Background Image/Video Field on Lens CT )
- [ ] Title (field_title -> short text)
- [ ] Background Media (field_bg_media -> Media Reference, Image and Video Allowed)
- [ ] Bubbles (field_bubbles -> Paragraph field that only allows Bubble paragraph type, multi value)

**Comment by ematsakov** [comment]
@pingevt 

Done.
http://pr-16-riveralive-cms.pantheonsite.io/admin/structure/paragraphs_type/wm_hotspot/fields
