### ISSUE TITLE
C Results Animal Updates

### ISSUE THREAD

**Issue by pingevt** [bluecadet/riveralive-cms#30]
- [ ] field_c_actions needs to be changed to a paragraph field referencing the NEW "C Action" Paragraph.
- [ ] Add field: Map Image (field_c_map_image -> Media Reference, Image only)
- [ ] Description for Map Image: "Image will be cropped to 960 x 1080"

**Comment by aostroverkhov** [comment]
@pingevt done, please check

**Comment by pingevt** [comment]
Looks Good, Thanks!
