### ISSUE TITLE
Watershed API endpoint

### ISSUE THREAD

**Issue by pingevt** [bluecadet/riveralive-cms#4]
- [ ] can add to ra_api module
- [ ] need path: 'api/watershed'
- [ ] Should pull in all published 'WM Lens' content and children/grand-children Paragraphs
- [ ] Simplify everything down the way we normally do

Example, but may not be 100% accurate:
```
[
nid: 2,
title: "Lens CT title,
field_lens_bg_media: [NOT SURE YET],
field_color: "color_name", [run through Html::cleanCssIdentifier()]
field_icon: "icon_name", [run through Html::cleanCssIdentifier()]
field_lens_hotspots: [
    {
      field_title: "Hotspot title",
      field_bg_media: [NOT SURE YET],
      [Co-ordinates],
      field_bubbles: [
        {
          field_body: "Body of the bubble",
          field_takeaway: "Takeaway of the bubble",
          [Co-ordinates],
        }
      ]
    }
 ]
]
```

**Comment by ematsakov** [comment]
@pingevt 
JSON structure contradicts with the "WM Lens CT" and "WM Hotspot Para Bundle" fields structure.

From the JSON structure above we can see that color and icon fields belong to hotspots paragraphs.

But from these 2 tasks https://github.com/bluecadet/riveralive-cms/issues/3 and https://github.com/bluecadet/riveralive-cms/issues/1 we can see these 2 fields belong to the "WM Lens" content type.

Could you please specify which case is correct?

**Comment by pingevt** [comment]
@ematsakov 
Sorry about that, I updated this description. In general the individual tickets should be the default.

**Comment by ematsakov** [comment]
@pingevt 

Done.
http://pr-16-riveralive-cms.pantheonsite.io/api/watershed
