### ISSUE TITLE
Update Hotspot module for Core Media

### ISSUE THREAD

**Issue by pingevt** [bluecadet/riveralive-cms#5]
You guys created a hotspot module for the MIT project a few months ago. I tried to enable on this project, and doesn't appear to be working at the moment. We are using the new Core Media module now and I have a feeling that may be the issue.

I think first step here would be to test and update the hotspot module.

**Comment by pingevt** [comment]
@ematsakov Looks good and working. We may need to tweak a little bit based on how we are doing this, but i need to keep working on the spec for this before we move like that. Thanks

**Comment by ematsakov** [comment]
@pingevt 

Clear, thanks!
Sorry, didn't have a chance to rebuild composer.lock yesterday for installing dependant modules, but I can see you did it, thanks.
Ok, will be waiting on additional info for future tweaks.
