### ISSUE TITLE
WM Bubble Para Bundle

### ISSUE THREAD

**Issue by pingevt** [bluecadet/riveralive-cms#8]
"WM Bubble" Para Bundle (wm_bubble)

- Body (field_body - long text no WYSIWYG)
- Takeaway (field_takeaway - long text no WYSIWYG)
- Image (field_bubble_image - Media reference, Image Media only) 

[Not sure exactly how you want to handle this... Let me know if you have any questions or want to discuss]
- [ ] (x,y) coords field (Spec from Alexey's team) ( referencing Background Image/Video Field on Hotspot Para )

**Comment by ematsakov** [comment]
@pingevt 

Done
http://pr-16-riveralive-cms.pantheonsite.io/admin/structure/paragraphs_type/wm_bubble/fields
